// piece/button.vue
<template>
  <nuxt-link
    v-bind:to="link"
    v-if="scope == ''"
    class="rounded-md flex bg-base-16 tracking-md w-full py-4 px-8 transition-colors justify-center items-center uppercase hover:bg-base-24"
  >
    <slot />
  </nuxt-link>

  <a
    v-else
    target="_blank"
    v-bind:href="link"
    class="rounded-md flex bg-base-16 tracking-md w-full py-4 px-8 transition-colors justify-center items-center uppercase hover:bg-base-24"
  >
    <slot />
  </a>
</template>

<script>
  export default {
    props: ['scope', 'link']
  }
</script>

// piece/button.svelte
<script lang="ts">
  export let link: string
  export let external: boolean = false
</script>

<a class="button" href={link} target={external ? '_blank' : undefined}>
  <slot />
</a>

<style lang="scss" global>
  .button {
    border-radius: pre.con(edge-rad);

    display: flex;
    align-items: center;
    justify-content: center;
    background-color: pre.con(base-16);

    width: 100%;
    padding: pre.rem(16) pre.rem(32);

    transition: background-color pre.con(time) pre.con(func);
  }

  .button:hover {
    background-color: pre.con(base-24);
  }
</style>
