// piece/button.vue
<template>
  <nuxt-link
    v-bind:to="link"
    v-if="scope == ''"
    class="rounded-md flex bg-base-16 tracking-md w-full py-4 px-8 transition-colors justify-center items-center uppercase hover:bg-base-24"
  >
    <slot />
  </nuxt-link>

  <a
    v-else
    target="_blank"
    v-bind:href="link"
    class="rounded-md flex bg-base-16 tracking-md w-full py-4 px-8 transition-colors justify-center items-center uppercase hover:bg-base-24"
  >
    <slot />
  </a>
</template>

<script>
  export default {
    props: ['scope', 'link']
  }
</script>

// source/piece/button.svelte
<script lang="ts">
  export let link: string
  export let external: boolean = false
</script>

<a class="button" href={link} target={external ? '_blank' : undefined}>
  <slot />
</a>

<style lang="scss" global>
  .button {
    display: flex;
    align-items: center;
    justify-content: center;

    width: 100%;
    border-radius: 4px;
    padding: 16px 32px;

    background-color: hsl(216 8% 16%);
    transition: background-color 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .button:hover {
    background-color: hsl(216 8% 24%);
  }
</style>
